## Домашнее задание

__Задание 1. Генератор случайных матриц.__

Реализовать генератор матриц, который должен поддерживать функции:
* Генерация абсолютно случайной матрицы $n\times m$
* Генерация случайной диагональной матрицы $n\times n$
* Генерация случайной верхнетреугольной матрицы
* Генерация случайной нижнетреугольной матрицы
* Генерация симметричной матрицы
* Генерация вырожденной матрицы
* Генерация матрицы ступенчатого вида $n\times n$ ранга $m$
* Генерация возмущения матрицы $n\times m$, каждый элемент которой не превосходит по модулю заданный $\varepsilon$. Оценить величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).

Оценить численно вероятность того, что созданная матрица будет вырожденной для какого-либо случая выше.

In [1]:
# Реализую произвольную m,n, верхнетреугольную и симметричную. Остальное на вас - вам нужно дописать функцию.
# Не забудьте откомментировать ваши изменения в документации к функции!

import numpy as np

def matrix_generate(rows, columns, type_ = "full", eps = 0):
    """
    matrix_generate(rows, columns, type_ = "full")

    Создаёт случайную матрицу выбранного типа.

    Если матрицу нужных размеров создать нельзя, должен выдать
    строку f"Error with type {type_} and shape ({rows},{columns})".

    Parameters
    ----------

    rows : int
        Количество строк в создаваемой матрице.
    columns : int
        Количество столбцов в создаваемой матрице.
    type_ : str, optional
        Тип создаваемой матрицы: "full", "upper_triangular", "symmetric" и т.д.
    eps: float, optional
        Дополнительное число, использующееся при генерации для некоторых типов матриц.

    Returns
    -------
    out : ndarray or str
        Выдаёт матрицу нужного типа либо ошибку.

    Notes
    -----
    Поддерживаемые типы матриц:
        "full","upper_triangular",
        "lower_triangular",
        "symmetric", "diagonal",
        "degenerate", "stepwise",
        "outrange"


    """

    A = None

    if type_ == "full":
        A = np.random.random(size=(rows, columns))

    elif type_ == "upper_triangular":
        A = np.random.random(size=(rows, columns))
        for i in range(rows):
            for j in range(columns):
                if (i > j):
                    A[i, j] = 0

    elif type_ == "lower_triangular":
        A = np.tril(np.random.random(size=(rows, columns)))
       
    elif type_ == "symmetric":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            a = np.random.random(size=(rows, columns))
            A = np.triu(a) + np.triu(a).T - np.tril(np.triu(a))
    
    elif type_ == "diagonal":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        A = np.diag(np.random.random(size=rows))
    
    elif type_ == "degenerate":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        a = np.random.random(size=(rows - 1, columns))
        A = np.concatenate((a, np.array(a[-1])), axis=0)

    elif type_ == "stepwise":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        elif eps > rows:
            return f"Error with type {type_} and shape ({rows},{columns})"
        elif eps < 0 or not str(eps).isdigit():
            return f"Error with type {type_} and shape ({rows},{columns})"
        a = matrix_generate(eps, eps, type_ = "upper_triangular")
        a = np.concatenate((a, matrix_generate(eps, columns - eps, type_ = "full")), axis=1)
        A = np.concatenate((a, np.zeros(shape=(rows-eps, columns))), axis=0)
    
    elif type_ == "outrage":
        A = np.random.uniform(low=-eps, high=eps, size=())
        
    return A

In [3]:
matrix_generate(1, 3)

array([[0.92729915, 0.46372064, 0.3302204 ]])

In [4]:
matrix_generate(4, 4, type_ = "upper_triangular")

array([[0.29095118, 0.48243508, 0.33314696, 0.11652231],
       [0.        , 0.38207998, 0.3216804 , 0.19134324],
       [0.        , 0.        , 0.19209787, 0.8512658 ],
       [0.        , 0.        , 0.        , 0.83580995]])

In [5]:
matrix_generate(4, 3, type_ = "upper_triangular")

array([[0.53609234, 0.36418414, 0.88111427],
       [0.        , 0.98355036, 0.59701315],
       [0.        , 0.        , 0.73738553],
       [0.        , 0.        , 0.        ]])

In [6]:
matrix_generate(4, 4, type_ = "symmetric")

array([[0.1556073 , 0.68119342, 0.99206063, 0.21796994],
       [0.68119342, 0.11418224, 0.15759881, 0.11224172],
       [0.99206063, 0.15759881, 0.70145001, 0.26590431],
       [0.21796994, 0.11224172, 0.26590431, 0.03111788]])

In [7]:
matrix_generate(4, 4, type_ = "diagonal")

array([[0.00487425, 0.        , 0.        , 0.        ],
       [0.        , 0.10497014, 0.        , 0.        ],
       [0.        , 0.        , 0.91900008, 0.        ],
       [0.        , 0.        , 0.        , 0.95536839]])

Будем использовать Манхэттенскую норму:

$||A|| \leq m \varepsilon$

максимум:

$||A|| \leq n \varepsilon$

Норма Фробениуса:

$||A|| \leq \sqrt{nm} \cdot \varepsilon$

Тогда оценка $n, m, \varepsilon$ подойдет для всех норм.
Для случая вырожденной матрицы вероятность вырожденности равна 1.

---

__Задание 2. Вычисление матричных норм и числа обусловленности.__

Реализовать вычисление трех основных норм векторов (L1, L2 и максимальную) и подчиненных им матричных норм. Реализовать вычисление числа обусловленности.

Примечание: для вычисления собственных значений можно использовать linalg.eigvals из модуля scipy.

In [30]:
import numpy as np
import scipy as sp

def L1_vec_norm(x):
    return np.sum(abs(x))

def L2_vec_norm(x):
    return np.linalg.norm(x)

def Max_vec_norm(x):
    return np.max(x)

def L1_mat_norm(A):
    return Max_mat_norm(A.T)

def L2_mat_norm(A):
    return np.sqrt(np.max(sp.linalg.eigvals(A.T @ A).real))

def Max_mat_norm(A):
    return np.max(np.sum(A, axis=1))

def conditionality_number(A, norm="L2"): # norm: "L1", "L2", "Max"
    m = None
    if norm == "L1":
        m = L1_mat_norm(A) * L1_mat_norm(np.linalg.inv(A))
    elif norm == "Max":
        m = Max_mat_norm(A) * Max_mat_norm(np.linalg.inv(A))
    elif norm == "L2":
        m = L2_mat_norm(A) * L2_mat_norm(np.linalg.inv(A))
    return m

x = np.array([6, -1, 2])
A = matrix_generate(2, 2, type_ = "symmetric")
A

array([[0.9591998 , 0.81803531],
       [0.81803531, 0.52950193]])

In [31]:
conditionality_number(A)

15.67742888291677

In [32]:
L2_vec_norm(x)

6.4031242374328485

---

__Задание 3. Эквивалентность первых двух норм.__

Найдите константы $C_1$  и  $C_2$ такие, что

$\ C_1||\mathbf{x}||_2\leq||\mathbf{x}||_1\leq C_2||\mathbf{x}||_2$


Указание: в качестве подсказки можно использовать визуализацию норм из документа с теорией.

**Решение**

Востользуемся неравенством Коши-Буняковского для двух векторов $x, y$:
    
$( x , y ) \leq |x|\cdot|y|)$

или

$x_1 y_1 + \ldots + x_n y_n \leq \sqrt{ x_1^2+ \ldots + x_n^2} \cdot \sqrt{ y_1^2 + \ldots + y_n^2}$

Это неравенство выполнено для любых $x, y$, поэтому взяв произвольный $x$ и подобрав к нему $y$: $y_i = \text{sgn }{ x_i }$, получаем следующее неравенство:

$|x_1| + \ldots +|x_n| \leq \sqrt n \sqrt{ x_1^2 + \ldots + x_n^2}$

Для получения $C_1$ достаточно возвести нормы в квадрат и увидеть, что квадрат первой
нормы равен сумме квадрата второго и неотрицательной суммы попарных произведений
модулей компонент.

**Ответ**

Таким образом, $C_1=1$, $C_2=\sqrt n$

---

__Задание 4. Евклидова и бесконечная норма.__

 Пусть x — вектор размерности m, а A — матрица m×n. Докажите следующие неравенства и приведите
примеры таких x и A, при которых неравенства обращаются в равенства:

- $\|x\|_2 \leq \sqrt{m} \cdot \|x\|_{\infty}$
- $\|A\|_{\infty} \leq \sqrt{n} \cdot \|A\|_2$

**Решение**

Первый пункт

$\|x \|_2 = \sqrt{ x_1^2+ \ldots + x_m^2} \leq \sqrt{ m \cdot \max{( x_1 , \ldots, x_m )}} = \sqrt m\cdot \| x \|_\infty  $
                                                                
Равенство очевидно выполняется, если все элементы равны.

Видим, что максимальная норма не больше нормы Фробениуса:

$\| A \| _\infty \leq \| A \|_F$.

При этом норму Фробениуса можно оценить с помощью спектральной нормы:

$\| A \|_F \leq \sqrt n \cdot \| A \|_2$ (как это было показано на семинаре)

---

__Задание 5.  Норма Фробениуса.__

Докажите, что для любой унитарной матрицы U (и для произвольной матрицы A) имеет место равенство

 $\| U A \|_F = \| AU \|_F = \| A \|_F$ ,

 где $\| \cdot \|_F$ — норма Фробениуса.

Указание.  
Задачу можно решить без вычислений, если использовать геометрический смысл нормы Фробениуса и геометрические свойства умножения на унитарную матрицу (что при умножении на неё сохраняется).

Используя свойства нормы и унитарных матриц:

$\|UA\|_F = \text{tr } (UA)^T UA =  \text{tr } A^T U^T U A= \text{tr } A^T A=\|A\|_F$

---

__Задание 6*.  Тензорная свёртка.__

Рассмотрим функцию, отображающую шесть тензоров на один тензор: $Z\left(\lambda^{(1)}, \lambda^{(2)}, \lambda^{(3)}, \Gamma^{(1)}, \Gamma^{(2)}, U\right)$ :


$$
Z_{a h i j}=\sum_{b c d e f g} \lambda^{(1)}{ }_{a b} \Gamma_{c b d}^{(1)} \lambda^{(2)}{ }_{d e} \Gamma_{f e g}^{(2)} \lambda_{g h}^{(3)} U_{i j c f}
$$

редположив, что все индексы пробегают значения от 1 до χ, проведите эксперимент и сравните скорость
различных реализаций функции Z. Исследуйте значения χ в диапазоне 3–50.


- В файле convolution. ipynb вы можете найти релизацию глупого способа вычисления этой свертки, который требует $\chi^4 \times \chi^6=\chi^{10}$ операций. На самом деле это можно вычислить гораздо быстрее!
- С помощью функции numpy . einsum (нужно использовать аргумент optimize), можно добиться намного большей производительности. Чтобы понять, что происходит под капотом, воспользуйтесь функцией numpy.einsum_path. Какое минимальное количество операций требуется для вычисления $Z$ ?
- Посмотрев на вывод функции numpy.einsum_path, peализуйте алгоритм для вычисления $Z$, который столь же эффективен, как numpy.einsum, но использует более элементарные numpy.dot и numpy.tensor_dot.


__Задание 7*__

Сгенерировать хорошо обусловленную матрицу (по сравнению со случайной)